### ISSUE TITLE
部署配置，缺少mongodb 数据库文件吧？

### ISSUE THREAD

**Issue by cong-long** [0xbug/Hawkeye#1]
嗨，这个项目似乎缺少了mongodb文件，不知道怎么创建呢？菜鸟不懂mongodb，望解答下！

**Comment by 0xbug** [comment]
@cong-long mongodb 安装了吗

**Comment by cong-long** [comment]
@0xbug 安装了的

**Comment by cong-long** [comment]
@0xbug 我解决了！！项目很不错，手动点赞！！

**Comment by toddpod** [comment]
@cong-long 请问怎么解决的，我遇到和你一样的问题

**Comment by Medicean** [comment]
@toddpod mongodb 设置好账号密码端就行了，不需要导任何数据，会自动初始化
