### ISSUE TITLE
“已确认” 功能bug

### ISSUE THREAD

**Issue by helloexp** [0xbug/Hawkeye#100]
### 描述
文件排查过程中，确认了一个，但是结果里面出现两个一样的
### 部署方式（Docker或其它）
Docker 本地编译
### 错误日志
![default](https://user-images.githubusercontent.com/21156949/51727289-483b0c00-20a6-11e9-891f-83262c813862.png)

贴上 `docker exec xxxx tail -f /var/log/supervisor/* ` 结果

**Comment by 0xbug** [comment]
确认操作会把同仓库其它文件一同标记

**Comment by helloexp** [comment]
了解了，感谢回复
