### ISSUE TITLE
使用nohup &后台运行，告警邮件不停的发送问题

### ISSUE THREAD

**Issue by mdsrc** [0xbug/Hawkeye#11]
如题，使用nohup创建了进程后台运行，配置了告警邮箱地址之后，邮件就不停的发送，请问有什么方法解决么

**Comment by 0xbug** [comment]
是 `Hawkeye.py` 还是 `spider.py`?

**Comment by mdsrc** [comment]
Hawkeye.py, 我看发送邮件的函数在spider.py里，应该给spider.py创建进程？

**Comment by 0xbug** [comment]
我想知道邮件的内容都一样吗

**Comment by UncleJim** [comment]
真有这种情况，而且已经忽略的仓库也会重复发送

**Comment by mdsrc** [comment]
是的，邮件内容发送后会重复发送，已忽略的仓库也会重复发送

**Comment by 0xbug** [comment]
加我微信`clin-lee`

**Comment by 0xbug** [comment]
@mdsrc pull一下最新代码，修复了这个问题

**Comment by mdsrc** [comment]
@0xbug 刚pull了新的代码，已经不再不停发邮件了
