### ISSUE TITLE
添加不进去github账户

### ISSUE THREAD

**Issue by biubiuniu** [0xbug/Hawkeye#119]
![捕获](https://user-images.githubusercontent.com/21076173/63828359-c511c980-c998-11e9-87d6-d076d474e95d.PNG)
无法添加，会报500错误。并且已经有3个月没有抓取到新数据了。
贴上 `docker exec xxxx tail -f /var/log/supervisor/* ` 结果

![image](https://user-images.githubusercontent.com/21076173/63828417-effc1d80-c998-11e9-9503-de2fd1c413da.png)

**Comment by 0xbug** [comment]
拉下最新版,然后访问 /api/health 贴下截图

**Comment by biubiuniu** [comment]
![image](https://user-images.githubusercontent.com/21076173/63829326-d3151980-c99b-11e9-807b-0b12c2f20275.png)

**Comment by biubiuniu** [comment]
前两天刚升级到最新版的，
![image](https://user-images.githubusercontent.com/21076173/63829348-df00db80-c99b-11e9-8cd2-9d8dcad9a9cb.png)

**Comment by 0xbug** [comment]
连接github超时了

**Comment by biubiuniu** [comment]
github连接超时应该不影响我把数据填入到本地数据库中吧。我本地数据库中没有显示

**Comment by 0xbug** [comment]
账号密码验证可用才会保存入库

**Comment by biubiuniu** [comment]
{"github":true,"mongodb":{"connectionId":342,"err":null,"n":0,"ok":1.0,"syncMillis":0,"writtenTo":null}}
联通了，十分感谢。现在应该没问题了
