### ISSUE TITLE
Error: Request failed with status code 400

### ISSUE THREAD

**Issue by toddpod** [0xbug/Hawkeye#12]
当我确认某个可疑项目准备提交时，选择“是否安全”、“忽略仓库”后，点击“确认”会报这个错误，请教是怎么回事？

**Comment by 0xbug** [comment]
服务端报什么错？

**Comment by toddpod** [comment]
服务端好像没有什么报错，可以看下
![image](https://user-images.githubusercontent.com/19703618/28812402-27744b2e-76c7-11e7-8c87-17ae4ad2ee4a.png)

**Comment by toddpod** [comment]
如果没有安装vuejs环境，是不是会导致点击确认后上述报错问题？

**Comment by 0xbug** [comment]
你可以看看命令行报没报错

**Comment by toddpod** [comment]
直接运行Hawkeye.py是正常的，安装npm的过程中出现错误。
![image](https://user-images.githubusercontent.com/19703618/28813713-1898a216-76cd-11e7-9aaa-dbfb4546ab00.png)

**Comment by 0xbug** [comment]
不需要安装vuejs,项目都已经编译好了，你再看看点击按钮后服务端有无报错

**Comment by toddpod** [comment]
点击后，看到服务端，没有任何提示，怀疑是不是fe/src/router/index.js中没有指定api/leakage的路径？
![image](https://user-images.githubusercontent.com/19703618/28816020-e1d271a4-76d5-11e7-8605-b917b331daea.png)

**Comment by 0xbug** [comment]
加我微信 `clin-lee`

**Comment by toddpod** [comment]
问题已经解决，感谢0xbug大牛
