### ISSUE TITLE
登录失败

### ISSUE THREAD

**Issue by chennqqi** [0xbug/Hawkeye#13]
手动在web上登录成功，但是填入配置文件config.ini提示登录失败，是github限制登录了吗

**Comment by 0xbug** [comment]
还有可能是你的搜索关键词有问题，`We could not perform this search`

**Comment by chennqqi** [comment]
了解了，搜索API返回的结果

**Comment by 0xbug** [comment]
换了其他关键词，成功了吗？

**Comment by chennqqi** [comment]
这个我昨天测了很久没发现什么规律,一般来说参数越少越不容易出错
page=1 时 s=indexed不一定是必须的，有时候后去掉可以成功
感觉他们api做了一定的限制，规律不明显。

搜索关键词每次用一个目前不报错

**Comment by 0xbug** [comment]
可以先在网页上搜索试试，是否有搜索结果; `s=indexed`是为了检索最新的

**Comment by chennqqi** [comment]
OK,谢谢，有发现就反馈给你
