### ISSUE TITLE
提个建议

### ISSUE THREAD

**Issue by chennqqi** [0xbug/Hawkeye#14]
建议增加黑名单按照文件名过滤
按照关键词过滤不如按照文件名效果好，可以一起并用

**Comment by 0xbug** [comment]
目前就是按照文件链接过滤的 （包括文件名）

**Comment by chennqqi** [comment]
确认，已经读过代码了。哈哈我自己加了个按照扩展名和正则过滤，但是不会做界面。。直接改spider
