### ISSUE TITLE
搭建成功点击关键词配置好了关键字为啥出现响应状态码500错误

### ISSUE THREAD

**Issue by whitetoday** [0xbug/Hawkeye#17]
搭建成功点击关键词配置好了关键字，刷新页面为啥出现响应状态码500错误，也没有看到监控的结果

**Comment by 0xbug** [comment]
服务端有报错信息吗

**Comment by whitetoday** [comment]
有报错信息，显示是这样的 ：GET /api/setting/cron  HTTP/1.1   500  -

**Comment by 0xbug** [comment]
把Python版本、系统、运行 `Hawkeye.py` 的用户贴上来

**Comment by whitetoday** [comment]
python版本是3.5.3 系统是CentOS6.8  运行Hawkeye.py的用户我都试过，包括普通用户和root用户，都会出现这样的情况

**Comment by 0xbug** [comment]
![image](https://user-images.githubusercontent.com/12611275/29510819-becb047c-868f-11e7-83f4-93f8ae79c4c6.png)
这两个按钮点击了吗

**Comment by whitetoday** [comment]
![image](https://user-images.githubusercontent.com/3281250/29511063-7b1fa006-8690-11e7-9bfb-b2922f7476e0.png)
点击了，也是500 状态码错误

**Comment by 0xbug** [comment]
加我微信聊吧 `clin-lee`

**Comment by chennqqi** [comment]
我这里也有这个问题，结果页面太多了就出这个问题了

**Comment by whitetoday** [comment]
感谢作者辛苦指导，问题解决，是由于系统运行 Hawkeye.py 的用户没有添加到/etc/cron.allow下导致，所以将用户添加至/etc/cron.allow即可
