### ISSUE TITLE
关键词配置了，时间也配置了，但是就是看不到结果

### ISSUE THREAD

**Issue by 0xLucifer** [0xbug/Hawkeye#18]
关键词配置了，时间和爬取深度也设置了，但是就是看不到结果

这种情况遇到好几次了，不知道什么原因

配置了大约几百个关键字吧，主页那里总是暂无数据。

crontab -l可以看到有内容

**Comment by chennqqi** [comment]
兄弟你手动执行下python spider.py 看看结果。。

**Comment by 0xLucifer** [comment]
我擦这么快回复

**Comment by 0xLucifer** [comment]
IndexError: list index out of range

**Comment by 0xbug** [comment]
是最新的代码吗

**Comment by 0xLucifer** [comment]
貌似被我搞定了，稍等一下我再测试一下。

**Comment by 0xLucifer** [comment]
Hi all，汇总一下我遇到的问题，希望有帮助：）
1、我是在2017年09月01日拉下的最新HawkEye代码
2、我直接安装了各种依赖库然后使用的，没用到virtualenv（对这个不太了解，直接用python3 Hawkeye.py 方式启动的）
3、导入了大约800+条关键字，配置了时间和爬取页数后，等了一段时间没有开始爬取，这点还不知道为什么
4、手动python3 spider.py可以爬到结果
5、在首页顶端"概览"上面可以看到有16条关键字的链接（低于我几百条的关键字数量，不知道是不是做了优化）

建议：
1、可以在页面上加一个手动开始爬的按钮，比如第一次建立任务后，这点我也不确定为什么没有立刻开始爬，所以这个建议可能比较主观
2、建议加一个页面，可以看到每个关键字爬取的情况，比如每个关键字是什么时间爬的，按计划任务爬了多少

总体感觉是个不错的项目，666个赞：）

**Comment by 0xbug** [comment]
后续加上统计及爬取情况

**Comment by 0xLucifer** [comment]
还有一个问题，就是当爬取页数很多以后，点击比较大的页数，比如总页数为70页，单击30页以上的时候，报500错。但是当单击小一点的页数，比如10的时候就没问题

**Comment by 0xbug** [comment]
@0xLucifer  https://mozillazg.github.io/2016/07/mongodb-overflow-sort-stage-buffered-data-usage-of-x-bytes-exceeds-internal-limit-of-33554432-bytes.html

**Comment by Nintyhundred** [comment]
也是没有结果显示

**Comment by Nintyhundred** [comment]
怎样开启这个监控的功能？也已经安装完成，配置完毕了。就是不启动。

**Comment by like9729** [comment]
单独执行spider成功，检查cron存在，但是爬不到东西
应该确认下crontab内的完整命令是否可以执行

因为源码的write_cron方法内，crontab是这样拼接的：
{0}/venv/bin/python {0}/spider.py 1 {1}
也就是说，如果你不用venv，{0}/venv/bin/python是个不存在的文件
需要修改一下{0}/venv/bin/python为你python的路径

**Comment by lishion** [comment]
确实是虚拟环境出现的问题，我之前也是虚拟环境没有配置好，谢谢提醒。 @like9729
