### ISSUE TITLE
关于结束进程在重启的问题

### ISSUE THREAD

**Issue by ydxred** [0xbug/Hawkeye#19]
结束解之后二次在无法启动时什么问题呢,我对python并不是太熟
root@ydxsec:/scan/Hawkeye# python Hawkeye.py 
Traceback (most recent call last):
  File "Hawkeye.py", line 5, in <module>
    from crontab import CronTab
ImportError: No module named crontab
root@ydxsec:/scan/Hawkeye#

**Comment by 0xbug** [comment]
1. Python 版本？

2. 是按照文档创建的Python虚拟环境吗，还是直接用的系统的Python

**Comment by ydxred** [comment]
之前ubentu14里面搭建了出现这个类问题  换成了kali还是这样,是按照文档创建的Python虚拟环境 但是pip是python2

**Comment by 0xbug** [comment]
系统里安装了Python3了吗

**Comment by wiwide-ops** [comment]
忘记问了，配置中的间隔是分钟吗

**Comment by 0xbug** [comment]
@wiwide-ops 是
