### ISSUE TITLE
运行后无结果，手动运行spider.py后出现错误提示

### ISSUE THREAD

**Issue by eridanus96** [0xbug/Hawkeye#20]
全程都是200，没有报错，但没有任何结果

(venv) root@eridanus:/Hawkeye# python spider.py
lenovo
Traceback (most recent call last):
  File "spider.py", line 211, in <module>
    crawl(query)
  File "spider.py", line 75, in crawl
    for page in range(int(sys.argv[1]), int(sys.argv[2])):
IndexError: list index out of range

请问这是出现了什么问题呢？感谢！

**Comment by 0xbug** [comment]
spider.py 需要两个参数
```
python spider.py 页码开始 页码结束
```

**Comment by eridanus96** [comment]
明白了，谢谢！
