### ISSUE TITLE
运行后spider.py进程出现N个且主进程Hawkeye.py总是无故挂掉

### ISSUE THREAD

**Issue by geilige** [0xbug/Hawkeye#22]
![image](https://user-images.githubusercontent.com/10125363/30737677-04395296-9fba-11e7-8dc8-744840c4a210.png)

**Comment by 0xbug** [comment]
页码数过多，会导致耗时很久，建议先手动设置cron任务，分开爬取

**Comment by geilige** [comment]
我以为你还在外面happy呢 哈哈 但是遇到主进程python Hawkeye.py会无缘无故挂 导致主页无法访问 这是为啥

**Comment by 0xbug** [comment]
[加个debug=True,看看有没有报错](https://github.com/0xbug/Hawkeye/blob/master/Hawkeye.py#L305)

**Comment by wiwide-ops** [comment]
这个工具是会一直不停的循环爬下去吗？还是爬一遍就停止了？如果是这样如何循环爬

**Comment by 0xbug** [comment]
@wiwide-ops 是利用系统的cron执行的定时任务，在配置页面配置周期，然后`crontab -l`看下配置成没成功
