### ISSUE TITLE
or and  not 语法咨询

### ISSUE THREAD

**Issue by wiwide-ops** [0xbug/Hawkeye#24]
![image](https://user-images.githubusercontent.com/32890577/31761916-30748a5a-b4ec-11e7-9dc8-3d0cf28c2cec.png)
这些语句怎么写 有例子吗？

另外在删除了关键字后爬取的python进行还在，还会收到删除掉的关键字的提示。

**Comment by 0xbug** [comment]
1. example:过滤掉 `www.wiwide.com` 可以这样写 [`"wiwide.com" NOT "www"`](https://github.com/search?o=desc&q=%22wiwide.com%22+NOT+%22www%22&s=indexed&type=Code&utf8=%E2%9C%93)
2. 可能在你删除关键字之前，爬虫还正在抓取该关键字

**Comment by wiwide-ops** [comment]
比如 过滤含有  test 或者含有 work的是不是要分开写？还是可以用语法

**Comment by 0xbug** [comment]
可以用语法，语法有逻辑条件限制（5次）

**Comment by wiwide-ops** [comment]
有参考的文档吗？

**Comment by 0xbug** [comment]
[https://help.github.com/categories/searching-for-information-on-github/](https://help.github.com/categories/searching-for-information-on-github/)

**Comment by wiwide-ops** [comment]
感谢！

**Comment by wiwide-ops** [comment]
"work" created:>2017-01-01

这样关键字 关于日期没有生效，不支持吗？

**Comment by 0xbug** [comment]
code 搜索 不支持 created
