### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by lx277856602** [0xbug/Hawkeye#25]
按安装说明搭建起来,后台设定一些条件,看起来也没有什么报错,可就是没有搜索结果.
手工执行spider,发现报错

> python3 spider.py

> (venv) [root@hawkeye Hawkeye]# python3 ./spider.py           
> test
> Traceback (most recent call last):
>   File "./spider.py", line 211, in <module>
>     crawl(query)
>   File "./spider.py", line 75, in crawl
>     for page in range(int(sys.argv[1]), int(sys.argv[2])):
> IndexError: list index out of range
这是Bug?

**Comment by 0xbug** [comment]
Duplicate of #20

**Comment by lx277856602** [comment]
厉害了,作者秒回啊,赞一个.
手动执行可以发现结果,但UI操作没动静,先手动用起来,后续抽空排查下

最后再说一句,这个工具很好用

**Comment by 0xbug** [comment]
看下mongodb里面有没有数据

**Comment by lx277856602** [comment]
谢谢楼主,问题解决了.
我是把程序文件和mongodb分别放在不同的容器中,在centos容器中单独安装了crontab,后来重装了一次crontab,一切OK了

再次感谢!
