### ISSUE TITLE
处理完的任务，在归档列表里面数量太多，会直接报500错误

### ISSUE THREAD

**Issue by Jamalmo** [0xbug/Hawkeye#27]
处理完的任务，在归档列表里面数量太多，查看后面的页数会直接报500错误
Error:Request failed  whit status code 500

**Comment by 0xbug** [comment]
@Jamalmo  [修改mongodb内存限制](https://github.com/0xbug/Hawkeye/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)

**Comment by Jamalmo** [comment]
已解决，谢谢
