### ISSUE TITLE
建议：能否加一个登录验证功能

### ISSUE THREAD

**Issue by freegit9527** [0xbug/Hawkeye#29]
建议加一个登录功能，放在外网也能增加安全性

**Comment by toddpod** [comment]
这个功能确实比较实用，项目已经加星了。

**Comment by 0xbug** [comment]
我们内部用的是基于ldap认证，所以开源时把认证部分去掉了。认证功能年前会加上，大家也可以看文档https://flask-basicauth.readthedocs.io/en/latest/ 自己先实现下
