### ISSUE TITLE
触发时间

### ISSUE THREAD

**Issue by kulozzzz** [0xbug/Hawkeye#3]
大佬，我启动了之后配置了关键字然后怎么触发他去爬啊？？在定时任务哪里？我在定时任务哪里配置了时间间隔为1，但是没见爬到东西然后也没看到有什么报错啊

**Comment by 0xbug** [comment]
1. 操作系统
2.python 版本
3.crontab -l 执行结果

**Comment by kulozzzz** [comment]
我已经跑起来了大佬，刚刚大概是我的测试关键字github上面没有

**Comment by 0xbug** [comment]
可以先搜索测试一下
