### ISSUE TITLE
二次开发

### ISSUE THREAD

**Issue by freegit9527** [0xbug/Hawkeye#32]
你好，我需要在菜单栏添加自己的二次开发内容，请问view里面的路由应该怎样加？比如我要加一个跳转的按钮，但是点击之后访问的是 /#/跳转，没法和后台交互

**Comment by 0xbug** [comment]
是和hawkeye的后台交互吗

**Comment by freegit9527** [comment]
是的，路由写在app/view.py

**Comment by 0xbug** [comment]
微信多少，我加你

**Comment by freegit9527** [comment]
base64：Zm9ydGVjMjAxNw==

**Comment by downtown12** [comment]
static/app.js是混淆后的代码，可否提供原版代码供二次开发。目前加了一个报表导出功能，但是无法融入到前端交互

**Comment by 0xbug** [comment]
@downtown12 项目前端使用的Vuejs， fe目录是前端源码

**Comment by downtown12** [comment]
@0xbug 感谢指导。现在正在在你的前端基础上开发自有功能。前后端联调遇到了问题：目前每次调试都是使用npm run build将前端代码打包，然后覆盖原有代码，这样遇到了一些问题找不到原因，也很耗时。可否直接在npm run dev时联调前后端，不过前端服务在8080端口，后端是5000端口。可否给些提示？我看你的用到了http-proxy-middleware这个包，请问在项目中如何使用？感谢

**Comment by 0xbug** [comment]
@downtown12 加个微信

**Comment by 0xbug** [comment]
1. 这里改成后端url https://github.com/0xbug/Hawkeye/blob/e06dd95240079e280558635f6b81c27cb9b4aadd/fe/src/commons/Global.vue#L2

2. 然后Flask 开启跨域支持 https://github.com/0xbug/Hawkeye/blob/e06dd95240079e280558635f6b81c27cb9b4aadd/Hawkeye.py#L6 https://github.com/0xbug/Hawkeye/blob/e06dd95240079e280558635f6b81c27cb9b4aadd/Hawkeye.py#L46

**Comment by downtown12** [comment]
感谢。用另一种方法解决了：在config/index.js中配置http-proxy-middleware代理。我的微信号是downtown12，感谢指导，求交流：）
