### ISSUE TITLE
关于Github搜索

### ISSUE THREAD

**Issue by henryhjx** [0xbug/Hawkeye#34]
可能和这个项目无关，但是还是想咨询下，如果我关键字需要设置搜索一个服务器的FQDN，但是Github默认是屏蔽.这种特殊符号的，导致关键字servername.com.cn返回结果会被拆分成servername com  cn这种AND关系。请教下这种情况怎么来优化搜索呢？

**Comment by 0xbug** [comment]
试试"servername.com.cn"呢

**Comment by henryhjx** [comment]
忘更，其实还是比较难 用“”标记有时好使，有时候还是会有问题

**Comment by 0xbug** [comment]
这个和 elasticsearch 的搜索特性有关 一些符号会被忽略

**Comment by 0xbug** [comment]
这个可以通过代码来改善，判断关键字是否在文件中完整出现

**Comment by henryhjx** [comment]
@0xbug 我代码小白，求指点更新
