### ISSUE TITLE
数据库清空需要删除哪几个表？

### ISSUE THREAD

**Issue by qbyyy** [0xbug/Hawkeye#35]
如题

**Comment by 0xbug** [comment]
进入mongo shell
`
use Hawkeye

db.dropDatabase()
`

**Comment by qbyyy** [comment]
@0xbug 删除以后，之前配置的关键字消失，但是主界面依旧能更新出内容。

**Comment by 0xbug** [comment]
爬虫的进程还在， 删库之前杀掉
`ps -ef |grep "spider.py"|awk '{print $2}'|xargs kill -9`

**Comment by qbyyy** [comment]
@0xbug 再次创建Hawkeye库的时候，失败，提示：root已经存在 src/mongo/shell.db.js:1081.
mongo数据库之前没了解过。。。

**Comment by qbyyy** [comment]
我直接添加关键字，数据库神奇的出现了。。。

**Comment by henryhjx** [comment]
借楼问，请问如何删除某个关键字的数据？我用一个模糊的关键字搜出来几万条，但是现在删了这个关键字以后，历史数据在概要里还在。怎么删？Mongodb没玩过，我用一个可视化工具Robo3T打开数据库之看到Collections有3个字段（blacklist，leakage，query），没有找到我要的字段啊

**Comment by 0xbug** [comment]
@henryhjx 
```
use Hawkeye
db.leakage.deleteMany({"tag":"关键字"})
```

**Comment by henryhjx** [comment]
执行了，无效，返回值
{
    "acknowledged" : true,
    "deletedCount" : 0.0
}
看上去应该是删除条目为0，不过我的写的关键字应该是正确的- -

**Comment by 0xbug** [comment]
@henryhjx 是关键字的名称不是具体值

**Comment by henryhjx** [comment]
@0xbug 是的，我的关键字和名称是一样的，不过有特殊字符例如： xxxx\xxx\     需要转义么？

**Comment by henryhjx** [comment]
@0xbug 解决了。。我后来找到了原始的JSON数据，原来我那个名称后面还有个空格- -
