### ISSUE TITLE
爬虫突然失效了

### ISSUE THREAD

**Issue by henryhjx** [0xbug/Hawkeye#37]
最近发现工具爬不出结果,麻烦看下是什么原因呢
ps 结果
![image](https://user-images.githubusercontent.com/32382561/35267477-5b672fe0-0061-11e8-987b-ccae4aad6836.png)
nohup.out:
![image](https://user-images.githubusercontent.com/32382561/35267568-af7271ee-0061-11e8-9590-532bcbf92ae4.png)

脚本是定时执行的，不过我单独运行spider.py也是在控制台显示不出结果。

**Comment by 0xbug** [comment]
cron命令被你手动修改过，所以程序取值的时候出错了

**Comment by henryhjx** [comment]
@0xbug 那也应该不会手动执行spider.py也返回不了结果吧？

**Comment by 0xbug** [comment]
手动执行spider.py有报错吗

**Comment by henryhjx** [comment]
没有报错，有搜索结果输出信息，但就是感觉控制台页面没有更新结果。

**Comment by henryhjx** [comment]
@0xbug 

调整了下中文输出，发现是有报错的：
[root@Ttest ~]# /root/Hawkeye/venv/bin/python /root/Hawkeye/spider.py 1 102
PROD app-msp-silverlining
登录失败

但是什么情况下会输出登录失败呢？我Github用户名密码和mongodb密码都是正确的。
