### ISSUE TITLE
我想增加关键字，比如要搜索在github上存在的mysql,oracle,pass等关键字

### ISSUE THREAD

**Issue by xiaoyanguoke** [0xbug/Hawkeye#39]
例如以百度为例。
baidu mysql
baidu oracle
baidu pass
能不能我在该项目中直接写成一行。

**Comment by 0xbug** [comment]
["baidu" AND ("pass" OR "oracle" OR "mysql")](https://github.com/search?p=1&q=%22baidu%22+AND+%28%22pass%22+OR+%22oracle%22+OR+%22mysql%22%29&type=Code&utf8=%E2%9C%93)

**Comment by xiaoyanguoke** [comment]
好的，谢谢。可以设置源文件的扩展名匹配吗，比如我只想要java，php，python等源代码里面包含上面的关键字

**Comment by 0xbug** [comment]
可以先用 https://github.com/search/advanced?q=%22baidu%22+AND+%28%22pass%22+OR+%22oracle%22+OR+%22mysql%22%29 把条件填好，然后搜索，复制搜索框里的就可以了
