### ISSUE TITLE
authenticity_token出现错误

### ISSUE THREAD

**Issue by xiaoyanguoke** [0xbug/Hawkeye#41]
![image](https://user-images.githubusercontent.com/15224735/37697144-17b71116-2d16-11e8-8d6b-fcaf7989d081.png)

![image](https://user-images.githubusercontent.com/15224735/37697167-37dc210c-2d16-11e8-9021-46521f6983fa.png)

**Comment by xiaoyanguoke** [comment]
我之前运行的好好的，最近几天没有收到邮件，然后重新测试了下Spider.py文件，发现这里报错如上，帮忙解决下，谢谢

**Comment by 0xbug** [comment]
pull 更新一下
