### ISSUE TITLE
github获取时间问题

### ISSUE THREAD

**Issue by xiaopopoxiao** [0xbug/Hawkeye#42]
web界面->首页出现的XX分钟前，XX小时前，第一次spider之后时间好像比较准确，等定时任务跑起来之后，时间不准确，反映在2个方面：
1. XX小时前说得不是代码更改的时候，而是代码所在repo更改的时间，也就是说如果同repo中其他文件出现了变化，也会提示变化
2. 完全不准确，XX小时前，点进去，github给出的时间明明是xx days ago，差别过大。
这会是什么原因呢？

**Comment by 0xbug** [comment]
代码更新后 ，github 需要更新搜索索引才能被搜到，这个时间是 github 更新搜索索引的时间，是晚于代码更新的时间的
![image](https://user-images.githubusercontent.com/12611275/37814575-9df671e6-2ea5-11e8-8b61-d0785753b78d.png)

![image](https://user-images.githubusercontent.com/12611275/37814483-3a86d16e-2ea5-11e8-9914-d27aeda80087.png)

**Comment by xiaopopoxiao** [comment]
哦，原来如此，谢谢作者，研读作者代码中
