### ISSUE TITLE
我搭建好了之后，设置好了关键词和计划任务

### ISSUE THREAD

**Issue by menglike** [0xbug/Hawkeye#43]
我搭建好了之后，设置好了关键词和计划任务，没有扫描记录 ，如何排错！

**Comment by 0xbug** [comment]
crontab -l, 手动执行cron中设置的任务，贴下报错 在2018年04月08日 12:06 ，menglike写道： 我搭建好了之后，设置好了关键词和计划任务，没有扫描记录 ，如何排错！ — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by menglike** [comment]
![Uploading image.png…]()
我看你的文档里没有写要跑计划任务， 暂时没有报错，可以进行数据库操作，应该不是数据库的问题

**Comment by menglike** [comment]
![image](https://user-images.githubusercontent.com/7685906/38463271-6722e0ba-3b29-11e8-93a6-f57b44388b22.png)


登录失败 但是我已经git pull

**Comment by menglike** [comment]
搭建好了 有个建议 就是首页最好能增加一个筛选  关键词太多的话 搜索结果会是指数级别的！

**Comment by menglike** [comment]
如何删除一个关键字的所有扫描记录

**Comment by 0xbug** [comment]
删除关键字即可

**Comment by menglike** [comment]
![image](https://user-images.githubusercontent.com/7685906/38464375-52258a08-3b3f-11e8-9ec9-a756110a61ef.png)
不对呀  关键字我删了 为什么还在跑呢

**Comment by 0xbug** [comment]
spider.py 在你删之前开始了爬取

**Comment by menglike** [comment]
那这种不需要的数据 如何删除？直接去mongo里面删？

**Comment by menglike** [comment]
找到 直接在mongodb中去改就行了
