### ISSUE TITLE
下一版更新计划

### ISSUE THREAD

**Issue by 0xbug** [0xbug/Hawkeye#44]
- [x] 受影响资产
![image](https://user-images.githubusercontent.com/12611275/38974763-d9494f00-43dd-11e8-87ab-400ab4da3bb0.png)
- [x] 爬虫任务状态、结果
- [x] 首页用户体验优化：支持多种过滤方式
![image](https://user-images.githubusercontent.com/12611275/38974717-bb180756-43dd-11e8-9544-9541fbf07693.png)
- [x] 添加开关，控制是否抓取 
![image](https://user-images.githubusercontent.com/12611275/38974815-0d3d8628-43de-11e8-9286-ecf40cdf17f9.png)

**Comment by 0xbug** [comment]
- [ ] 通知方式添加

- [ ] 邮件样式优化

- [ ] ldap 支持

**Comment by 0xbug** [comment]
@gitPAWJ 根据文档重新配置了吗？

**Comment by gitPAWJ** [comment]
![snipaste_2018-04-20_20-05-43](https://user-images.githubusercontent.com/38219256/39050019-52cc5068-44d6-11e8-8771-b7e37a855ab5.jpg)
@0xbug 请问是在红框那块点击处理吗？点击没反应 ，我重新配置了显示和爬虫都没有问题

**Comment by 0xbug** [comment]
什么浏览器，用Chrome 试试

**Comment by gitPAWJ** [comment]
谢谢@0xbug Chrome 可以，辛苦了，周末愉快！

**Comment by 0xbug** [comment]
Firefox 有这个问题，等到家我解决一下

**Comment by 0xbug** [comment]
@gitPAWJ 老哥更新一下吧，解决了

**Comment by liutao123321** [comment]
2018-04-25 11:39:09,258 [Hawkeye] [CRITICAL] list index out of range 爬虫出问题了？

**Comment by Githubsectest** [comment]
2018-05-03 10:30:20,734 [Hawkeye] [CRITICAL] list index out of range  老哥，相同的问题

**Comment by 0xbug** [comment]
@Githubsectest @liutao123321 是偶发的，还是连续都这样？

**Comment by Githubsectest** [comment]
@0xbug @liutao123321 已经可以了，谢谢大佬，加个参数就可以了  python spider.py 1 5

**Comment by 1tstec** [comment]
请问大佬，后端的5000端口怎么修改，在哪个配置文件中，请指教

**Comment by 0xbug** [comment]
@1tstec 

修改 ` Hawkeye.py` https://github.com/0xbug/Hawkeye/blob/c3e88f177923529e88bf0c254f05054f649a7445/Hawkeye.py#L347
```
    app.run(threaded=True, port=int(sys.argv[1]), host='0.0.0.0', use_reloader=True)
```

然后运行时指定端口参数 
`python Hawkeye.py 8888`

**Comment by 1tstec** [comment]
大佬，我看介绍里面写到了mongo，如果不配mongo是不是会爆500的错？是不是必须装mongo啊~

**Comment by 0xbug** [comment]
@1tstec 爬取的数据是放到mongo里的

**Comment by 1tstec** [comment]
@0xbug 我配置了一条搜索语法，时间间隔是5,爬取页数是30，是说每隔5分钟自动用config.ini中的github账户登录一次，爬取30页相关的信息吗？目前概览页上没有任何信息，是说配置完后任务5分钟以后启动吗？

**Comment by 1tstec** [comment]
跑了几个任务，爆了一个数据库的错误：Sort operation used more than the maximum 33554432 bytes of RAM，查了一下是Mongodb的sort操作是把数据拿到内存中再进行排序的，为了节约内存，默认给sort操作限制了最大内存为32Mb，当数据量越来越大直到超过32Mb的时候就抛出异常了
请问 @0xbug 大佬，这个问题你遇到过不。。。怎么解决。。。

**Comment by 0xbug** [comment]
@1tstec wiki里面有

**Comment by 1tstec** [comment]
@0xbug 大佬，怎么把待处理里面的结果加到已处理或者归档，我怎么没找到按钮或者操作的地方，请大佬明示，多谢多谢

**Comment by 0xbug** [comment]
@1tstec 查看详情里面有

**Comment by 1tstec** [comment]
@0xbug 多谢多谢
