### ISSUE TITLE
请问有没有日志？

### ISSUE THREAD

**Issue by MumuRao** [0xbug/Hawkeye#46]
请问有没有日志？

**Comment by 0xbug** [comment]
logs/spider.log

**Comment by 0xbug** [comment]
@scannerkun  手动运行spider.py需要两个参数：开始页码和结束页码
`python spider.py 1 2 `

**Comment by scannerkun** [comment]
老兄，加个微信呗 18701039418

2018-05-15 

scanner 



发件人：0xbug <notifications@github.com>
发送时间：2018-05-15 10:25
主题：Re: [0xbug/Hawkeye] 请问有没有日志？ (#46)
收件人："0xbug/Hawkeye"<Hawkeye@noreply.github.com>
抄送："scannerkun"<scanner@sina.com>,"Mention"<mention@noreply.github.com>

@scannerkun 手动运行spider.py需要两个参数：开始页码和结束页码
python spider.py 1 2
