### ISSUE TITLE
我的一直没有数据。。。

### ISSUE THREAD

**Issue by ekko-zhao** [0xbug/Hawkeye#47]
单独跑了下sprider,日志如下：
![image](https://user-images.githubusercontent.com/26781518/40346680-2c50c0be-5dd0-11e8-8d95-fc1359936d3d.png)
![image](https://user-images.githubusercontent.com/26781518/40346718-4539f578-5dd0-11e8-9b1f-fd67dd865557.png)
配置文件：

![qq 20180522150024](https://user-images.githubusercontent.com/26781518/40346900-e23bf736-5dd0-11e8-948d-4eb237bbf541.jpg)

老哥，感谢答疑

**Comment by 0xbug** [comment]
日志太少

**Comment by ekko-zhao** [comment]
日志就只有前面有错误信息，后面的都是解析的网页。
我看了下进程：
![image](https://user-images.githubusercontent.com/26781518/40349883-8cb28726-5dda-11e8-9d6c-2a55383ba3a8.png)
似乎爬虫bing并没有起来，只有一个Hawkeye.py
![image](https://user-images.githubusercontent.com/26781518/40350063-2533e36e-5ddb-11e8-99f9-f1aee77cee6f.png)
看这里也发现爬虫确实没有工作。。。

**Comment by 0xbug** [comment]
要先在前端的设置里配置定时任务，是利用cron 定时执行 spider.py  的

**Comment by ekko-zhao** [comment]
![image](https://user-images.githubusercontent.com/26781518/40350265-df43e77c-5ddb-11e8-936e-b6bf54816caf.png)
是这个吗，配置是可以的。

**Comment by gtdreamlife** [comment]
@ekko-zhao 哥们，这个问题最后是咋解决的，页面编辑crontab以后就好了？

**Comment by 0xbug** [comment]
@gtdreamlife 点击页面按钮，程序会自动添加定时任务

**Comment by gtdreamlife** [comment]
@0xbug 我的是之前正常爬着的，也是通过页面编辑了定时任务，只是今天发现搜索失败，账号登录没问题，数据库改成了500M，爬取页面数设置成40页，还是一样，之前正常的时候是30分钟爬一次

**Comment by gtdreamlife** [comment]
遇到的问题类似，也是在前端页面，设置爬取时间和页面以后，点击确认修改成功，但是定时任务并没有执行spider.py，全部删除以后重装还是一样
