### ISSUE TITLE
爬虫报错“[CRITICAL] list index out of range”

### ISSUE THREAD

**Issue by Hudi233** [0xbug/Hawkeye#58]
您好
在运行爬虫的时候报错
[CRITICAL] list index out of range

![image](https://user-images.githubusercontent.com/20939673/43391895-8ab9e934-9424-11e8-95b0-e36a965bb59a.png)

请问可能的原因是什么呢？

**Comment by 0xbug** [comment]
已修复 https://github.com/0xbug/Hawkeye/commit/056a0807b258fc7396095f0e190fa2f8113f0381
