### ISSUE TITLE
 list index out of range

### ISSUE THREAD

**Issue by tao3323225** [0xbug/Hawkeye#63]
[Hawkeye] [CRITICAL] list index out of range
装了几次，都有类似的问题

**Comment by BouteilleKwok** [comment]
也遇到这个问题，解决了么

**Comment by tao3323225** [comment]
还没有。。。

**Comment by BouteilleKwok** [comment]
是crawl函数 下面标注的部分报的错，超过8个，就会报错

def crawl(query):
    session = create_session()
    search_url = 'https://github.com/search?o=desc&p={}&q={}&ref=searchresults&s=indexed&type=Code&utf8=%E2%9C%93'
    for page in range(int(sys.argv[1]), int(sys.argv[2])):
        try:
            logger.info('start crawl: tag is {}, page is {}'.format(query.get('tag'), page))

            resp = session.get(
                search_url.format(
                    page, query['keyword']))
        except Exception as error:
            logger.critical(error)
            query_col.update_one({'tag': query['tag']},
                                 {'$set': {'status': -1, 'last': int(time.time()), 'reason': error}})
            resp = session.get(
                search_url.format(
                    page, query['keyword']))

        if get_conf('GitHub', 'ERROR') in resp.text:
            logger.critical('搜索失败: {}'.format(resp.text))

            query_col.update_one({'tag': query['tag']},
                                 {'$set': {'last': int(time.time()), 'status': -1, 'reason': '搜索失败'}})

            exit(0)
        tree = etree.HTML(resp.text)
        nodes = tree.xpath(get_conf('Leakage', 'NODES'))
        #print(nodes)
        for node in nodes:
            try:
                node_index = nodes.index(node) + 1
                print('00')
#------------------------------------------------------------------
                **in_blacklist = False
                leakage = {}
                leakage['datetime'] = node.xpath(
                    get_conf('Leakage', 'DATETIME').format(
                        node_index))[0].attrib['datetime']**
# -------------------------------------------------------------
                leakage['link'] = 'https://github.com{}'.format(
                    node.xpath(get_conf('Leakage', 'LINK').format(node_index))[
                        0].attrib['href'])
                leakage['project'] = node.xpath(
                    get_conf('Leakage', 'PROJECT').format(node_index))[0].text
                leakage['_id'] = md5(leakage['link'])

**Comment by tao3323225** [comment]
怎么改？

**Comment by 0xbug** [comment]
今天会对项目进行重构，修复此类问题

**Comment by blue-bird1** [comment]
问题已知 @0xbug  项目使用的xpath 会把下面的分页也匹配进去

**Comment by blue-bird1** [comment]
修复方案 ·配置文件修改至 `NODES =  //*[@id="code_search_results"]/div[@class="code-list"]/div[*]`
