### ISSUE TITLE
请问一下发送不了告警邮件怎么解决呢？

### ISSUE THREAD

**Issue by AngieQ1** [0xbug/Hawkeye#69]
邮件告警已经开启，也配置了服务器和端口，邮箱和授权码，但是扫描完后没有收到告警邮件。

**Comment by lordsky** [comment]
> 邮件告警已经开启，也配置了服务器和端口，邮箱和授权码，但是扫描完后没有收到告警邮件。

你可以查看一下日志是不是因为包含关键词拦截了，我之前用163的是这样的
