### ISSUE TITLE
supervisor好像不支持py3吧？

### ISSUE THREAD

**Issue by DrizzleRisk** [0xbug/Hawkeye#7]
如题，supervisor好像不支持py3吧？有已经实践的解决方案没？

**Comment by 0xbug** [comment]
你那边部署在什么系统，我这边debian用apt-get安装，改下[配置文件](https://github.com/0xbug/Hawkeye/blob/master/deploy/Hawkeye.conf.example)中的路径就可以了

**Comment by DrizzleRisk** [comment]
CentOS

![image](https://user-images.githubusercontent.com/6161410/28262332-358f4c76-6b15-11e7-9bae-d1b23b2994ed.png)

**Comment by 0xbug** [comment]
这个是在虚拟环境里执行`pip install supervisor` 的报错吗

**Comment by DrizzleRisk** [comment]
解决了，用python2装，可以在python3下使用，另外用gunicorn似乎应该用相对路径才可以启动成功

**Comment by 0xbug** [comment]
假设项目位于`/data/Hawkeye`

做如下修改就可以了（gunicorn安装在虚拟环境里）

```
[program:Hawkeye]
command=/data/Hawkeye/venv/bin/gunicorn -w4 -b0.0.0.0:5000 Hawkeye:app
directory=/data/Hawkeye
startsecs=0
stopwaitsecs=0
autostart=true
autorestart=true
```
