### ISSUE TITLE
请问配置好关键词之后如何进行扫描，还有时间间隔是什么

### ISSUE THREAD

**Issue by tianmin99** [0xbug/Hawkeye#73]
配置完关键词之后怎么样可以开始扫描，控制台没有结果啊

**Comment by lordsky** [comment]
配置好之后每割n分钟会自动扫描，n等于你自己设的。
    扫描完成后关键词有会有更新的，x分钟前扫描过
       或者你去服务器的logs下去看，有日志记录的

**Comment by lordsky** [comment]
> 配置完关键词之后怎么样可以开始扫描，控制台没有结果啊


配置好之后每割n分钟会自动扫描，n等于你自己设的。扫描完成后关键词有会有更新的，x分钟前扫描过或者你去服务器的logs下去看，有日志记录的
--
