### ISSUE TITLE
时常500状态码

### ISSUE THREAD

**Issue by Imanfeng** [0xbug/Hawkeye#74]
您好 请问时常500如何解决呢
![2018-09-16 5 32 43](https://user-images.githubusercontent.com/24694387/45594980-b3792100-b9d6-11e8-990a-167b62d9301a.png)
![2018-09-16 5 32 55](https://user-images.githubusercontent.com/24694387/45594984-ba079880-b9d6-11e8-98e1-0603f68e5862.png)

**Comment by Gotric** [comment]
使用python3执行

**Comment by snappyJack** [comment]
我也是遇到这个问题

**Comment by snappyJack** [comment]
解决了
