### ISSUE TITLE
初始化后出现500错误

### ISSUE THREAD

**Issue by kartfran** [0xbug/Hawkeye#77]
### 描述
初始化后弹出500错误，无法添加关键字。（初步判断数据库连接异常）
![image](https://user-images.githubusercontent.com/6095163/47211806-10e30200-d3c9-11e8-93e8-c1af0e7ba644.png)
### 部署方式（Docker或其它）
docker run -ti -p 80:80 -e MONGODB_URI=mongodb://username:password@ip:27017/hawkeye -e MONGODB_USER=xxxx -e MONGODB_PASSWORD=xxxx -d hawkeye

### 错误日志

贴上 `docker exec xxxx tail -f /var/log/supervisor/* ` 结果
![image](https://user-images.githubusercontent.com/6095163/47211917-5dc6d880-d3c9-11e8-9751-2c4579219bad.png)

**Comment by 0xbug** [comment]
贴一下 `docker exec xxx curl mongo的ip:端口 ` 结果
