### ISSUE TITLE
超过一定（220左右）数量数据，页面无法显示

### ISSUE THREAD

**Issue by HyWell** [0xbug/Hawkeye#78]
### 描述
mongodb默认内存设置为32MB，超过上限之后会报错，建议说明该情况并创建索引。
### 部署方式（Docker或其它）
Docker
### 错误日志
pymongo.errors.OperationFailure: Executor error during find command :: caused by :: Sort operation used more than the maximum 33554432 bytes of RAM. Add an index, or specify a smaller limit.

贴上 `docker exec xxxx tail -f /var/log/supervisor/* ` 结果
<img width="841" alt="default" src="https://user-images.githubusercontent.com/21263451/47346460-d8e90100-d6df-11e8-8dd1-d8ef1a11a61b.png">

**Comment by 0xbug** [comment]
wiki 里有相关说明，后期会完善文档

**Comment by scannerkun** [comment]
现在有最近版本了吗？最新版本怎么更新？




发件人：0xbug <notifications@github.com>
发送时间：2018-10-23 16:48
主题：Re: [0xbug/Hawkeye] 超过一定（220左右）数量数据，页面无法显示 (#78)
收件人："0xbug/Hawkeye"<Hawkeye@noreply.github.com>
抄送："Subscribed"<subscribed@noreply.github.com>

wiki 里有相关说明，后期会完善文档
