### ISSUE TITLE
error

### ISSUE THREAD

**Issue by popmedd** [0xbug/Hawkeye#8]
[2017-07-17 17:25:19,610] ERROR in app: Exception on /api/setting/cron [GET]
Traceback (most recent call last):
  File "/opt/Hawkeye/venv/lib/python3.4/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/Hawkeye/venv/lib/python3.4/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/Hawkeye/venv/lib/python3.4/site-packages/flask_restful/__init__.py", line 480, in wrapper
    resp = resource(*args, **kwargs)
  File "/opt/Hawkeye/venv/lib/python3.4/site-packages/flask/views.py", line 84, in view
    return self.dispatch_request(*args, **kwargs)
  File "/opt/Hawkeye/venv/lib/python3.4/site-packages/flask_restful/__init__.py", line 595, in dispatch_request
    resp = meth(*args, **kwargs)
  File "Hawkeye.py", line 235, in get
    return jsonify({'status': 200, 'msg': '获取信息成功', 'result': read_cron()})
  File "Hawkeye.py", line 285, in read_cron
    user_cron = CronTab(user=True)
TypeError: __init__() got an unexpected keyword argument 'user'

**Comment by 0xbug** [comment]
是什么用户运行的 Hawkeye.py

**Comment by popmedd** [comment]
root用户

**Comment by 0xbug** [comment]
把Hawkeye.py第285行的`user_cron = CronTab(user=True)`改成`user_cron = CronTab()`试试

**Comment by popmedd** [comment]
File "Hawkeye.py", line 235, in get
    return jsonify({'status': 200, 'msg': '获取信息成功', 'result': read_cron()})
  File "Hawkeye.py", line 285, in read_cron
    user_cron = CronTab()
TypeError: __init__() missing 1 required positional argument: 'crontab'

**Comment by LillyLin2016** [comment]
请问能不能对待处理的进行归档、删除等操作呢？

**Comment by 0xbug** [comment]
@LillyLin2016 请单独新建个issue

**Comment by 0xbug** [comment]
改成user_cron = CronTab('root')试试

**Comment by popmedd** [comment]
File "/opt/Hawkeye/venv/lib/python3.4/site-packages/crontab/_crontab.py", line 166, in _assert
    raise ValueError(message%args)
ValueError: invalid range specifier: 'root' ('root')

**Comment by 0xbug** [comment]
什么系统、系统版本，我这边用Python3.4 也没复现

**Comment by popmedd** [comment]
Linux ubuntu 4.2.0-16

**Comment by 0xbug** [comment]
加微信私聊吧：`clin-lee`

**Comment by 0xbug** [comment]
卸载 `crontab` 安装 `python-crontab` 解决问题
https://github.com/doctormo/python-crontab
```
Note: If you get the error TypeError: __init__() takes exactly 2 arguments when using CronTab, you have the wrong module installed. You need to install python-crontab and not crontab from pypi or your local package manager and try again.
```

**Comment by volts1983** [comment]
我也遇到了同样的问题。 
问题是：
  File "Hawkeye.py", line 280, in get
    return jsonify({'status': 200, 'msg': '获取信息成功', 'result': read_cron()})
  File "Hawkeye.py", line 331, in read_cron
    user_cron = CronTab(user=True)
TypeError: __init__() got an unexpected keyword argument 'user'

我做了两种应对，都有这个问题。 
    329 def read_cron():
    330     #user_cron = CronTab(user='root')
    331     user_cron = CronTab(user=True)

我安装的crontab包如下：
 pip freeze
aniso8601==3.0.2
backports.ssl-match-hostname==3.4.0.2
certifi==2017.7.27.1
chardet==3.0.4
Cheetah==2.4.4
click==6.7
cloud-init==0.7.6
configobj==4.7.2
configparser==3.5.0
crontab==0.22.1
decorator==3.4.0
Flask==1.0.2
Flask-BasicAuth==0.2.0
Flask-Login==0.4.1
Flask-RESTful==0.3.6
idna==2.6
iniparse==0.4
itsdangerous==0.24
Jinja2==2.10
jsonpatch==1.16
jsonpointer==1.10
Markdown==2.6.8
MarkupSafe==1.0
oauth==1.0.1
perf==0.1
prettytable==0.7.2
pycurl==7.19.0
pygobject==3.14.0
pygpgme==0.3
pyliblzma==0.5.3
pymongo==3.6.1
pyparsing==1.5.6
python-crontab==2.3.4
python-dateutil==2.7.3
pytz==2018.4
pyudev==0.15
pyxattr==0.5.1
PyYAML==3.12
requests==2.18.4
six==1.11.0
slip==0.4.0
slip.dbus==0.4.0
urlgrabber==3.10
urllib3==1.22
Werkzeug==0.14.1
yum-metadata-parser==1.1.4
You are using pip version 9.0.1, however version 10.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
