### ISSUE TITLE
这个项目能不能监控其他的代码平台

### ISSUE THREAD

**Issue by 18736738152** [0xbug/Hawkeye#80]
最近公司也需要监控其他的代码平台，想问一下有什么好的解决办法

**Comment by 18736738152** [comment]
最近公司也需要监控其他的代码平台，想问一下有什么好的解决办法

**Comment by 0xbug** [comment]
还有其它支持代码级别检索的平台吗

**Comment by 18736738152** [comment]
> 还有其它支持代码级别检索的平台吗
我在网上找了一些，码云，gitlab，coding.net,有的好像不支持

**Comment by 0xbug** [comment]
除了github其它平台不支持代码级别检索
