### ISSUE TITLE
调试环境出现查询引擎为“离线”，setting模块rule不显示配置项，其他正常

### ISSUE THREAD

**Issue by hahadaxia** [0xbug/Hawkeye#95]
### 描述
调试环境发现，result模块的查询引擎一直显示为“离线”，setting模块部分rule一直不显示，配置项。
### 部署方式
调试环境

**Comment by Explorer1092** [comment]
贴上 `docker exec xxxx tail -f /var/log/supervisor/* ` 结果

**Comment by hahadaxia** [comment]
docker环境是可以的 目前是pycharm调试的时候出现的问题

**Comment by hahadaxia** [comment]
> 贴上 `docker exec xxxx tail -f /var/log/supervisor/* ` 结果
docker环境是可以的 目前是pycharm调试的时候出现的问题

**Comment by ChinaSrc** [comment]
解决了吗？请问怎么处理的
