### ISSUE TITLE
是否有非Docker的部署教程

### ISSUE THREAD

**Issue by xiaochao** [0xbug/Hawkeye#98]
如题，不用dockek，如何部署了？可否写个简单的教程。

**Comment by buddyho** [comment]
同问。
网上有非docker部署方式，但一步步照做到最后，
启动hawkeye:
#python Hawkeye.py
才发现没有Hawkeye.py文件，也是醉了。。。

**Comment by 0xbug** [comment]
可以 参考 https://github.com/0xbug/Hawkeye/blob/master/Dockerfile 进行部署

**Comment by buddyho** [comment]
> 可以 参考 https://github.com/0xbug/Hawkeye/blob/master/Dockerfile 进行部署

小白一枚，可否给个稍祥细点的攻略...
